feat:Add trivy, certmanager, sealed secret and their values files

diff --git a/.github/workflows/infra-argocd.yml b/.github/workflows/infra-argocd.yml
--- a/.github/workflows/infra-argocd.yml
+++ b/.github/workflows/infra-argocd.yml
@@ -85,9 +85,9 @@ jobs:
       - name: Verificar ficheros requeridos
         run: |
           set -euo pipefail
-          test -f infra/deploy_argocd.sh || { echo "[ERROR] No existe infra/deploy_argocd.sh"; exit 1; }
+          test -f infra/scripts/deploy_argocd.sh || { echo "[ERROR] No existe infra/scripts/deploy_argocd.sh"; exit 1; }
           test -f "$VALUES_FILE" || { echo "[ERROR] No existe values file: $VALUES_FILE"; exit 1; }
-          bash -n infra/deploy_argocd.sh
+          bash -n infra/scripts/deploy_argocd.sh
 
       - name: Verificar conectividad con cluster
         run: |
@@ -100,7 +100,7 @@ jobs:
           kubectl get nodes -o wide
 
       - name: Dar permisos al script
-        run: chmod +x infra/deploy_argocd.sh
+        run: chmod +x infra/scripts/deploy_argocd.sh
 
       - name: Ejecutar despliegue de Argo CD
-        run: ./infra/deploy_argocd.sh
+        run: ./infra/scripts/deploy_argocd.sh
diff --git a/.github/workflows/infra-lab.yml b/.github/workflows/infra-lab.yml
--- a/.github/workflows/infra-lab.yml
+++ b/.github/workflows/infra-lab.yml
@@ -97,9 +97,9 @@ jobs:
       - name: Verificar ficheros requeridos
         run: |
           set -euo pipefail
-          test -f infra/deploy_ingress.sh || { echo "[ERROR] No existe infra/deploy_ingress.sh"; exit 1; }
+          test -f infra/scripts/deploy_ingress.sh || { echo "[ERROR] No existe infra/scripts/deploy_ingress.sh"; exit 1; }
           test -f "$VALUES_FILE" || { echo "[ERROR] No existe values file: $VALUES_FILE"; exit 1; }
-          bash -n infra/deploy_ingress.sh
+          bash -n infra/scripts/deploy_ingress.sh
 
       - name: Verificar conectividad con cluster
         run: |
@@ -112,10 +112,10 @@ jobs:
           kubectl get nodes -o wide
 
       - name: Dar permisos al script
-        run: chmod +x infra/deploy_ingress.sh
+        run: chmod +x infra/scripts/deploy_ingress.sh
 
       - name: Desplegar NGINX Ingress con Helm
-        run: ./infra/deploy_ingress.sh
+        run: ./infra/scripts/deploy_ingress.sh
 
   infra-argocd:
     name: 3) Infra Argo CD
